name: Build BBC Disk Creator

jobs:
  build:
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Check-out repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Debug - List files
        run: |
          echo "Current directory:"
          pwd
          echo "Files in directory:"
          ls -la
          echo "Python version:"
          python --version

      - name: Build Executable with Nuitka
        uses: Nuitka/Nuitka-Action@v1.3
        with:
          nuitka-version: latest
          script-name: makedisk.py
          mode: onefile
          onefile-tempdir-spec: "%TEMP%"

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ runner.os }} Build
          path: | # match what's created for the 3 OSes
            makedisk.dist/*.exe
            makedisk.dist/*.bin
            makedisk.dist/*.app/**/*
            makedisk.dist/makedisk
          include-hidden-files: true
